[supabase]
url = "https://yfcrgjsouqtuilolztbl.supabase.co"
key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlmY3JnanNvdXF0dWlsb2x6dGJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgxMjgxNDAsImV4cCI6MjA3MzcwNDE0MH0.Ogln110aJlYTDucRoFrzjFlBTBTTWHXODWiRP4zd98s"